@startuml
actor Client1
actor Client2
actor Client3
actor Client4
participant Server

Client1 -> Server: connect
Server -> Client1: ack
note right of Server: Update: Add Client1 to player list
Client2 -> Server: connect
Server -> Client2: ack
note right of Server: Update: Add Client2 to player list
Client3 -> Server: connect
Server -> Client3: ack
note right of Server: Update: Add Client3 to player list
Client4 -> Server: connect
Server -> Client4: ack
note right of Server: Update: Add Client4 to player list

loop Player Guess
    ClientX -> Server: guess(object)
    note right of Server: Check deck of cards
    Server -> ClientX: validate(guess)
    alt Guess Correct
        note right of Server: Update matrix with correct guess
        Server -> All: broadcast(correct guess)
    else Guess Incorrect
        alt All eliminated
            note right of Server: Update matrix with server's matrix
            Server -> All: broadcast(matrix)
        else Not All eliminated
            note right of Server: Continue the game with the rest of players
        end
        Server -> All: broadcast(false guess - lost the game)
    end
end

Server -> All: update(game state)
@enduml
